export type StrengthExercise = {
  name: string;
  sets: number;
  reps?: number;
  durationSec?: number;
  perSide?: boolean;
  note?: string;
};

export type StrengthSessionDef = {
  category: "legs" | "chest" | "back";
  phase: "base" | "build" | "peak";
  name: string;
  description: string;
  exercises: StrengthExercise[];
};

export type BikeSessionDef = {
  category: "speed" | "endurance";
  phase: "base" | "build" | "peak" | "any";
  name: string;
  description: string;
  durationMin: number;
  focus: string;
};

export const STRENGTH_SESSIONS: StrengthSessionDef[] = [
  // ===== LEGS (12) =====
  {
    category: "legs",
    phase: "base",
    name: "Heavy Squat Foundation",
    description: "Week 1. Build the base — moderate loads, clean technique.",
    exercises: [
      { name: "Back Squat", sets: 4, reps: 8 },
      { name: "Romanian Deadlift", sets: 3, reps: 10 },
      { name: "Leg Press", sets: 3, reps: 10 },
      { name: "Walking Lunge", sets: 3, reps: 10, perSide: true },
      { name: "Standing Calf Raise", sets: 4, reps: 12 },
    ],
  },
  {
    category: "legs",
    phase: "base",
    name: "Squat + Posterior",
    description: "Week 2. Squat plus posterior chain work.",
    exercises: [
      { name: "Back Squat", sets: 4, reps: 6 },
      { name: "Good Morning", sets: 3, reps: 8 },
      { name: "Hip Thrust", sets: 3, reps: 10 },
      { name: "Nordic Curl", sets: 3, reps: 8 },
      { name: "Seated Calf Raise", sets: 4, reps: 12 },
    ],
  },
  {
    category: "legs",
    phase: "base",
    name: "Squat Strength",
    description: "Week 3. 5x5 squat, unilateral accessory.",
    exercises: [
      { name: "Back Squat", sets: 5, reps: 5 },
      { name: "Front Squat", sets: 3, reps: 6 },
      { name: "Romanian Deadlift", sets: 3, reps: 8 },
      { name: "Split Squat", sets: 3, reps: 8, perSide: true },
      { name: "Standing Calf Raise", sets: 4, reps: 10 },
    ],
  },
  {
    category: "legs",
    phase: "base",
    name: "Max Effort Lower",
    description: "Week 4. Squat + deadlift in the same session.",
    exercises: [
      { name: "Back Squat", sets: 4, reps: 5 },
      { name: "Deadlift", sets: 3, reps: 5 },
      { name: "Leg Extension", sets: 3, reps: 12 },
      { name: "Leg Curl", sets: 3, reps: 12 },
      { name: "Standing Calf Raise", sets: 4, reps: 12 },
    ],
  },
  {
    category: "legs",
    phase: "build",
    name: "Volume Squat",
    description: "Week 5. Higher volume, heavier loads.",
    exercises: [
      { name: "Back Squat", sets: 5, reps: 5 },
      { name: "Front Squat", sets: 3, reps: 6 },
      { name: "Bulgarian Split Squat", sets: 3, reps: 8, perSide: true },
      { name: "Leg Press", sets: 3, reps: 12 },
      { name: "Standing Calf Raise", sets: 4, reps: 15 },
    ],
  },
  {
    category: "legs",
    phase: "build",
    name: "Unilateral Focus",
    description: "Week 6. Single-leg strength and balance.",
    exercises: [
      { name: "Bulgarian Split Squat", sets: 4, reps: 6, perSide: true },
      { name: "Single Leg RDL", sets: 3, reps: 8, perSide: true },
      { name: "Step-up", sets: 3, reps: 8, perSide: true },
      { name: "Single Leg Press", sets: 3, reps: 10, perSide: true },
      { name: "Single Leg Calf Raise", sets: 3, reps: 12, perSide: true },
    ],
  },
  {
    category: "legs",
    phase: "build",
    name: "Volume Push",
    description: "Week 7. High-volume squat block.",
    exercises: [
      { name: "Back Squat", sets: 6, reps: 4 },
      { name: "Front Squat", sets: 4, reps: 6 },
      { name: "Leg Press", sets: 4, reps: 10 },
      { name: "Hack Squat", sets: 3, reps: 8 },
      { name: "Standing Calf Raise", sets: 4, reps: 15 },
    ],
  },
  {
    category: "legs",
    phase: "build",
    name: "Max Volume",
    description: "Week 8. Peak volume before shift to strength.",
    exercises: [
      { name: "Back Squat", sets: 5, reps: 6 },
      { name: "Romanian Deadlift", sets: 4, reps: 8 },
      { name: "Walking Lunge", sets: 3, reps: 12, perSide: true },
      { name: "Leg Curl", sets: 4, reps: 10 },
      { name: "Standing Calf Raise", sets: 5, reps: 12 },
    ],
  },
  {
    category: "legs",
    phase: "peak",
    name: "Power Squat",
    description: "Week 9. Heavy triples, explosive work.",
    exercises: [
      { name: "Back Squat", sets: 5, reps: 3 },
      { name: "Box Jump", sets: 4, reps: 3, note: "Max height, full recovery between sets" },
      { name: "Front Squat", sets: 3, reps: 5 },
      { name: "Hip Thrust", sets: 3, reps: 6 },
      { name: "Standing Calf Raise", sets: 3, reps: 12 },
    ],
  },
  {
    category: "legs",
    phase: "peak",
    name: "Explosive Lower",
    description: "Week 10. Speed-strength, paused work.",
    exercises: [
      { name: "Back Squat", sets: 5, reps: 3, note: "3s pause in the hole" },
      { name: "Jump Squat", sets: 4, reps: 4, note: "Bodyweight or light bar" },
      { name: "Romanian Deadlift", sets: 3, reps: 5 },
      { name: "Leg Press", sets: 3, reps: 8 },
      { name: "Standing Calf Raise", sets: 3, reps: 10 },
    ],
  },
  {
    category: "legs",
    phase: "peak",
    name: "Peak Strength",
    description: "Week 11. Near-max work, low volume.",
    exercises: [
      { name: "Back Squat", sets: 5, reps: 2 },
      { name: "Front Squat", sets: 3, reps: 3 },
      { name: "Deadlift", sets: 3, reps: 3 },
      { name: "Leg Curl", sets: 3, reps: 8 },
      { name: "Standing Calf Raise", sets: 3, reps: 10 },
    ],
  },
  {
    category: "legs",
    phase: "peak",
    name: "Taper Lower",
    description: "Week 12. Keep the snap, drop the fatigue.",
    exercises: [
      { name: "Back Squat", sets: 3, reps: 3, note: "Light, fast — 60-70% 1RM" },
      { name: "Split Squat", sets: 2, reps: 8, perSide: true },
      { name: "Leg Curl", sets: 2, reps: 10 },
      { name: "Standing Calf Raise", sets: 2, reps: 12 },
    ],
  },

  // ===== CHEST (12) =====
  {
    category: "chest",
    phase: "base",
    name: "Bench Foundation",
    description: "Week 1. Moderate-rep bench and accessories.",
    exercises: [
      { name: "Bench Press", sets: 4, reps: 8 },
      { name: "Incline Dumbbell Press", sets: 3, reps: 10 },
      { name: "Dips", sets: 3, reps: 10 },
      { name: "Lateral Raise", sets: 3, reps: 12 },
      { name: "Tricep Pushdown", sets: 3, reps: 12 },
    ],
  },
  {
    category: "chest",
    phase: "base",
    name: "Incline Focus",
    description: "Week 2. Upper chest and overhead work.",
    exercises: [
      { name: "Incline Bench Press", sets: 4, reps: 8 },
      { name: "Flat Dumbbell Press", sets: 3, reps: 10 },
      { name: "Overhead Press", sets: 3, reps: 8 },
      { name: "Rear Delt Flye", sets: 3, reps: 12 },
      { name: "Skullcrusher", sets: 3, reps: 10 },
    ],
  },
  {
    category: "chest",
    phase: "base",
    name: "Volume Push",
    description: "Week 3. High-rep push volume.",
    exercises: [
      { name: "Bench Press", sets: 4, reps: 10 },
      { name: "Dumbbell Bench Press", sets: 3, reps: 10 },
      { name: "Push-up", sets: 3, reps: 12 },
      { name: "Lateral Raise", sets: 4, reps: 12 },
      { name: "Rope Pushdown", sets: 3, reps: 12 },
    ],
  },
  {
    category: "chest",
    phase: "base",
    name: "Bench Strength",
    description: "Week 4. 5x5 bench, close-grip work.",
    exercises: [
      { name: "Bench Press", sets: 5, reps: 5 },
      { name: "Close-Grip Bench Press", sets: 3, reps: 6 },
      { name: "Incline Dumbbell Press", sets: 3, reps: 8 },
      { name: "Overhead Press", sets: 3, reps: 6 },
      { name: "Tricep Extension", sets: 3, reps: 10 },
    ],
  },
  {
    category: "chest",
    phase: "build",
    name: "Heavy Bench",
    description: "Week 5. Heavier loads, strength bias.",
    exercises: [
      { name: "Bench Press", sets: 5, reps: 5 },
      { name: "Incline Bench Press", sets: 4, reps: 6 },
      { name: "Dips", sets: 4, reps: 8 },
      { name: "Lateral Raise", sets: 4, reps: 10 },
      { name: "Skullcrusher", sets: 3, reps: 8 },
    ],
  },
  {
    category: "chest",
    phase: "build",
    name: "Push Volume",
    description: "Week 6. High volume for hypertrophy.",
    exercises: [
      { name: "Bench Press", sets: 6, reps: 5 },
      { name: "Incline Dumbbell Press", sets: 4, reps: 8 },
      { name: "Push-up", sets: 3, reps: 15 },
      { name: "Cable Flye", sets: 3, reps: 12 },
      { name: "Rope Pushdown", sets: 3, reps: 12 },
    ],
  },
  {
    category: "chest",
    phase: "build",
    name: "Overhead Focus",
    description: "Week 7. Shoulder-led push.",
    exercises: [
      { name: "Overhead Press", sets: 5, reps: 5 },
      { name: "Bench Press", sets: 4, reps: 6 },
      { name: "Arnold Press", sets: 3, reps: 8 },
      { name: "Lateral Raise", sets: 4, reps: 12 },
      { name: "Tricep Extension", sets: 3, reps: 10 },
    ],
  },
  {
    category: "chest",
    phase: "build",
    name: "Max Bench",
    description: "Week 8. Heavy triples, close-grip focus.",
    exercises: [
      { name: "Bench Press", sets: 5, reps: 3 },
      { name: "Close-Grip Bench Press", sets: 4, reps: 5 },
      { name: "Incline Dumbbell Press", sets: 3, reps: 6 },
      { name: "Dips", sets: 3, reps: 8 },
      { name: "Tricep Pushdown", sets: 3, reps: 10 },
    ],
  },
  {
    category: "chest",
    phase: "peak",
    name: "Power Bench",
    description: "Week 9. Paused bench + plyo.",
    exercises: [
      { name: "Bench Press", sets: 5, reps: 3, note: "1s pause on chest" },
      { name: "Incline Bench Press", sets: 3, reps: 4 },
      { name: "Dips", sets: 3, reps: 5 },
      { name: "Overhead Press", sets: 3, reps: 5 },
      { name: "Skullcrusher", sets: 3, reps: 8 },
    ],
  },
  {
    category: "chest",
    phase: "peak",
    name: "Explosive Push",
    description: "Week 10. Speed bench work.",
    exercises: [
      { name: "Bench Press", sets: 5, reps: 3 },
      { name: "Speed Bench", sets: 4, reps: 3, note: "60% 1RM, max bar speed" },
      { name: "Push-up", sets: 3, reps: 10, note: "Explosive" },
      { name: "Lateral Raise", sets: 3, reps: 10 },
      { name: "Tricep Pushdown", sets: 3, reps: 10 },
    ],
  },
  {
    category: "chest",
    phase: "peak",
    name: "Peak Bench",
    description: "Week 11. Near-max doubles.",
    exercises: [
      { name: "Bench Press", sets: 5, reps: 2 },
      { name: "Overhead Press", sets: 3, reps: 3 },
      { name: "Close-Grip Bench Press", sets: 3, reps: 3 },
      { name: "Dips", sets: 3, reps: 6 },
      { name: "Tricep Pushdown", sets: 2, reps: 10 },
    ],
  },
  {
    category: "chest",
    phase: "peak",
    name: "Taper Push",
    description: "Week 12. Light, crisp, fresh.",
    exercises: [
      { name: "Bench Press", sets: 3, reps: 3, note: "Light, 60-70% 1RM" },
      { name: "Push-up", sets: 2, reps: 10 },
      { name: "Lateral Raise", sets: 2, reps: 12 },
      { name: "Tricep Pushdown", sets: 2, reps: 12 },
    ],
  },

  // ===== BACK (12) =====
  {
    category: "back",
    phase: "base",
    name: "Deadlift Foundation",
    description: "Week 1. Deadlift plus vertical and horizontal pull.",
    exercises: [
      { name: "Deadlift", sets: 4, reps: 6 },
      { name: "Pull-up", sets: 3, reps: 8 },
      { name: "Barbell Row", sets: 3, reps: 10 },
      { name: "Face Pull", sets: 3, reps: 12 },
      { name: "Barbell Curl", sets: 3, reps: 10 },
    ],
  },
  {
    category: "back",
    phase: "base",
    name: "Volume Pull",
    description: "Week 2. Higher volume, mixed grips.",
    exercises: [
      { name: "Deadlift", sets: 4, reps: 5 },
      { name: "Chin-up", sets: 3, reps: 8 },
      { name: "Dumbbell Row", sets: 3, reps: 10, perSide: true },
      { name: "Lat Pulldown", sets: 3, reps: 12 },
      { name: "Hammer Curl", sets: 3, reps: 10 },
    ],
  },
  {
    category: "back",
    phase: "base",
    name: "Deadlift + Row",
    description: "Week 3. Thickness focus.",
    exercises: [
      { name: "Deadlift", sets: 4, reps: 5 },
      { name: "T-Bar Row", sets: 3, reps: 8 },
      { name: "Lat Pulldown", sets: 3, reps: 10 },
      { name: "Rear Delt Flye", sets: 3, reps: 12 },
      { name: "EZ-Bar Curl", sets: 3, reps: 10 },
    ],
  },
  {
    category: "back",
    phase: "base",
    name: "Pull Strength",
    description: "Week 4. 5x5 deadlift, heavy rows.",
    exercises: [
      { name: "Deadlift", sets: 5, reps: 5 },
      { name: "Pull-up", sets: 3, reps: 6 },
      { name: "Barbell Row", sets: 4, reps: 6 },
      { name: "Face Pull", sets: 3, reps: 12 },
      { name: "Barbell Curl", sets: 3, reps: 8 },
    ],
  },
  {
    category: "back",
    phase: "build",
    name: "Heavy Pull",
    description: "Week 5. Weighted pull-ups, heavy rows.",
    exercises: [
      { name: "Deadlift", sets: 5, reps: 5 },
      { name: "Weighted Pull-up", sets: 3, reps: 5 },
      { name: "Barbell Row", sets: 4, reps: 6 },
      { name: "Chest-Supported Row", sets: 3, reps: 8 },
      { name: "Hammer Curl", sets: 3, reps: 8 },
    ],
  },
  {
    category: "back",
    phase: "build",
    name: "Back Width",
    description: "Week 6. Vertical pull volume.",
    exercises: [
      { name: "Pull-up", sets: 5, reps: 6 },
      { name: "Lat Pulldown", sets: 4, reps: 8 },
      { name: "Dumbbell Row", sets: 4, reps: 8, perSide: true },
      { name: "Face Pull", sets: 4, reps: 12 },
      { name: "Cable Curl", sets: 3, reps: 10 },
    ],
  },
  {
    category: "back",
    phase: "build",
    name: "Back Thickness",
    description: "Week 7. Heavy horizontal pull.",
    exercises: [
      { name: "Deadlift", sets: 5, reps: 3 },
      { name: "Barbell Row", sets: 4, reps: 6 },
      { name: "T-Bar Row", sets: 4, reps: 8 },
      { name: "Shrug", sets: 3, reps: 10 },
      { name: "Preacher Curl", sets: 3, reps: 8 },
    ],
  },
  {
    category: "back",
    phase: "build",
    name: "Max Pull",
    description: "Week 8. Heavy triples, Pendlay rows.",
    exercises: [
      { name: "Deadlift", sets: 5, reps: 3 },
      { name: "Weighted Pull-up", sets: 4, reps: 4 },
      { name: "Pendlay Row", sets: 4, reps: 5 },
      { name: "Face Pull", sets: 3, reps: 12 },
      { name: "Barbell Curl", sets: 3, reps: 8 },
    ],
  },
  {
    category: "back",
    phase: "peak",
    name: "Power Pull",
    description: "Week 9. Heavy singles area, rack pulls.",
    exercises: [
      { name: "Deadlift", sets: 4, reps: 3 },
      { name: "Rack Pull", sets: 3, reps: 3 },
      { name: "Pull-up", sets: 3, reps: 6 },
      { name: "Cable Row", sets: 3, reps: 8 },
      { name: "Hammer Curl", sets: 3, reps: 8 },
    ],
  },
  {
    category: "back",
    phase: "peak",
    name: "Explosive Pull",
    description: "Week 10. Speed deadlifts, fast bar.",
    exercises: [
      { name: "Deadlift", sets: 5, reps: 2 },
      { name: "Speed Deadlift", sets: 4, reps: 3, note: "60% 1RM, maximal speed" },
      { name: "Pull-up", sets: 3, reps: 5 },
      { name: "Dumbbell Row", sets: 3, reps: 8, perSide: true },
      { name: "Barbell Curl", sets: 3, reps: 10 },
    ],
  },
  {
    category: "back",
    phase: "peak",
    name: "Peak Pull",
    description: "Week 11. Near-max pulling.",
    exercises: [
      { name: "Deadlift", sets: 4, reps: 2 },
      { name: "Weighted Pull-up", sets: 3, reps: 3 },
      { name: "Barbell Row", sets: 3, reps: 5 },
      { name: "Shrug", sets: 3, reps: 8 },
      { name: "Barbell Curl", sets: 2, reps: 10 },
    ],
  },
  {
    category: "back",
    phase: "peak",
    name: "Taper Pull",
    description: "Week 12. Fresh legs for race week.",
    exercises: [
      { name: "Deadlift", sets: 3, reps: 3, note: "Light, 60-70% 1RM" },
      { name: "Pull-up", sets: 2, reps: 6 },
      { name: "Face Pull", sets: 2, reps: 12 },
      { name: "Barbell Curl", sets: 2, reps: 10 },
    ],
  },
];

export const BIKE_SESSIONS: BikeSessionDef[] = [
  // ===== SPEED (12) =====
  {
    category: "speed",
    phase: "base",
    name: "Cadence Spin-ups",
    description: "60min Z2 with 4x1min at 110+rpm. Train leg speed for crit attacks.",
    durationMin: 60,
    focus: "Cadence",
  },
  {
    category: "speed",
    phase: "base",
    name: "Standing Sprints",
    description: "Warm-up + 6x15s max sprints from standing start, 3min recovery.",
    durationMin: 50,
    focus: "Sprint",
  },
  {
    category: "speed",
    phase: "base",
    name: "Rolling Sprints",
    description: "8x30s all-out from rolling start, 4min recovery. Race-start sim.",
    durationMin: 60,
    focus: "Sprint",
  },
  {
    category: "speed",
    phase: "build",
    name: "Over-Unders",
    description: "3x(4min FTP + 4x20s @ 130% FTP). Anaerobic repeatability.",
    durationMin: 75,
    focus: "Anaerobic",
  },
  {
    category: "speed",
    phase: "build",
    name: "VO2 Intervals",
    description: "5x3min @ 110% FTP, 3min recovery. Big engine builder.",
    durationMin: 70,
    focus: "VO2max",
  },
  {
    category: "speed",
    phase: "build",
    name: "Crit Microbursts",
    description: "2 sets of 10x(30s on / 30s off), 8min easy between sets.",
    durationMin: 65,
    focus: "VO2max",
  },
  {
    category: "speed",
    phase: "build",
    name: "Anaerobic Capacity",
    description: "6x1min @ 120% FTP, 2min recovery. Mimics crit attacks.",
    durationMin: 60,
    focus: "Anaerobic",
  },
  {
    category: "speed",
    phase: "build",
    name: "Race Opener Sim",
    description: "Hard 10min start at threshold, then 30min steady threshold.",
    durationMin: 75,
    focus: "Threshold",
  },
  {
    category: "speed",
    phase: "peak",
    name: "Crit Simulation A",
    description: "8x2min @ 120% FTP with 90s recovery. Pure crit-specific work.",
    durationMin: 75,
    focus: "Race-pace",
  },
  {
    category: "speed",
    phase: "peak",
    name: "Attack Practice",
    description: "4x(5min Z4 + 1min all-out attack), 5min easy between blocks.",
    durationMin: 80,
    focus: "Race-pace",
  },
  {
    category: "speed",
    phase: "peak",
    name: "Full Race Sim",
    description: "45min simulation with 4x1min max attacks spread through.",
    durationMin: 60,
    focus: "Race",
  },
  {
    category: "speed",
    phase: "peak",
    name: "Pre-Race Sharpener",
    description: "45min with 3x1min efforts. Legs primed, nothing draining.",
    durationMin: 45,
    focus: "Taper",
  },

  // ===== ENDURANCE (8) =====
  {
    category: "endurance",
    phase: "any",
    name: "Easy Z2",
    description: "Easy 60min Z2 conversational pace. Recovery ride.",
    durationMin: 60,
    focus: "Recovery",
  },
  {
    category: "endurance",
    phase: "base",
    name: "Long Z2 (90)",
    description: "90min Z2 endurance. Build the diesel engine.",
    durationMin: 90,
    focus: "Z2",
  },
  {
    category: "endurance",
    phase: "base",
    name: "Long Z2 (120)",
    description: "2hr Z2 endurance. Mid-volume base ride.",
    durationMin: 120,
    focus: "Z2",
  },
  {
    category: "endurance",
    phase: "base",
    name: "Long Z2 (150)",
    description: "2.5hr Z2. Peak endurance volume.",
    durationMin: 150,
    focus: "Z2",
  },
  {
    category: "endurance",
    phase: "build",
    name: "Sweetspot",
    description: "90min with 2x20min at Sweetspot (88-94% FTP).",
    durationMin: 90,
    focus: "Sweetspot",
  },
  {
    category: "endurance",
    phase: "any",
    name: "Endurance + Strides",
    description: "2hr Z2 with 6x20s fast strides mixed in.",
    durationMin: 120,
    focus: "Z2",
  },
  {
    category: "endurance",
    phase: "any",
    name: "Recovery Spin",
    description: "45min very easy. Active recovery only.",
    durationMin: 45,
    focus: "Recovery",
  },
  {
    category: "endurance",
    phase: "peak",
    name: "Openers",
    description: "60min with 4x30s easy openers. Keep the snap.",
    durationMin: 60,
    focus: "Openers",
  },
];
